version: '3'

services:
  bash:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./:/shared
    working_dir: /shared
    pid: host
